### ISSUE TITLE
Vents turned off by default

### ISSUE THREAD

**Issue by Dekserrrrrr** [CrowOfBourbon/NMF-Persephone#10]
vents are turned off by default

![Screenshot_676](https://user-images.githubusercontent.com/92396228/152960642-e3064f14-08ba-45d3-937b-eb0a2fa9fb76.png)

**Comment by CrowOfBourbon** [comment]
Hmmmmmmmmmmmmmmmmmmmmmmmmm I'll figure this out today.

**Comment by Dekserrrrrr** [comment]
Should note, it's only in this area and a room to the left. Every other vent works fine.

**Comment by CrowOfBourbon** [comment]
Placed an APC in the area and now they MIRACULOUSLY work
