### ISSUE TITLE
Chemistry Place Holder Problem

### ISSUE THREAD

**Issue by CrowOfBourbon** [CrowOfBourbon/NMF-Persephone#15]
[09:11:05]bad index
[09:11:05]proc name: process reactions (/datum/reagents/proc/process_reactions)
[09:11:05]  source file: Chemistry-Holder.dm,99

Grinders don't work

**Comment by Eyeveri** [comment]
I'll look into this.

**Comment by Eyeveri** [comment]
> 

What is the direct issue?

**Comment by CrowOfBourbon** [comment]
I wish I knew. This is what pops up when you load the world. Grinders won't work, either.

**Comment by CrowOfBourbon** [comment]
This has been fixed. Grinders LITERALLY have a stroke if they're in a room with no APC. it doesn't matter if the room has power. Grinders give no fucks about it.

They demand APC's. 

Whatever. Closing this. Map's been fixed for it!
