### ISSUE TITLE
Wall Sprites aren't EXISTING WITH THE NEW

### ISSUE THREAD

**Issue by CrowOfBourbon** [CrowOfBourbon/NMF-Persephone#16]
We have new wall sprites. Wall sprites are not in game, despite code having it everywhere a wall sprite should wall spritey

**Comment by Eyeveri** [comment]
Can you elaborate further for me?

**Comment by CrowOfBourbon** [comment]
Sprites are in the wall and wall mask icons but when you load the game to play, they aren't the correct wall.
