### ISSUE TITLE
Test/actual issue

### ISSUE THREAD

**Issue by Dekserrrrrr** [CrowOfBourbon/NMF-Persephone#8]
To make sure our issues work, also Royal, the red space carp in the HoS office has Ginny's description

![Screenshot_674](https://user-images.githubusercontent.com/92396228/152945008-98dcc958-5c14-4ecc-8eeb-84b59bd50011.png)

![Screenshot_675](https://user-images.githubusercontent.com/92396228/152945018-daa966ab-c4ef-41f3-9471-46c5976f7482.png)

**Comment by Eyeveri** [comment]
!fix
