### ISSUE TITLE
Maintenance access door that leads toward the merchant store has no access

### ISSUE THREAD

**Issue by Dekserrrrrr** [CrowOfBourbon/NMF-Persephone#85]
![image](https://user-images.githubusercontent.com/92396228/159243415-bfe16fa5-5b3a-41ef-b808-74ed1a1ec027.png)

**Comment by Alexeivichi** [comment]
This door basically has it that anyone can access it.

**Comment by MioBright** [comment]
Should be fixed with my update. Will close if fixed.
